server:
  port: 8081

dubbo:
  application:
    name: dubbo-springboot-quickstart-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.huey.learning.dubbo.quickstart.springboot.provider